### ISSUE TITLE
crypto.getRandomValues() not supported

### ISSUE THREAD

**Issue by fukemy** [hosseinmd/react-signalr#7]
hi i got this error when invoke method with params, can u help? 

```
 LOG  onOpen vsRxCEDPUSHnm4Cj0mEKfg
 LOG  _CreateRegisterClientObj params {"ClientId": "60016949-876f-43d6-abf4-8ace9a2a36cf", "DataStr": {"SessionId": "7EAFBC4D-3403-4C68-9443-8B1E9BB702C7", "Type": 4000}, "Type": 1}

 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
```

here is my code:
![Screen Shot 2022-06-08 at 13 59 01](https://user-images.githubusercontent.com/8202437/172552299-c2944ae4-ab04-48e2-8e5a-a3dd1f0b5590.png)

**Comment by hosseinmd** [comment]
Install [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values#readme)
Import it before uuid. Since uuid might also appear as a transitive dependency of some other imports it's safest to just import react-native-get-random-values as the very first thing in your entry point:
```js
import 'react-native-get-random-values';
```

**Comment by fukemy** [comment]
tks it's work
